### PR TITLE
and opeartor instead of nested if

### PR DESCRIPTION
**Pull request by bundle555**

### CODE REVIEW

**Review by garvit-joshi — APPROVED** [review]

**Comment by garvit-joshi** [comment]
Thanks @bundle555 for pointing out and refactoring the code.

**Comment by bundle555** [comment]
I'm learning C++. Can you tell me why you open two files before deleting a file.

**Comment by garvit-joshi** [comment]
It was done to check if files are present in the directory, you can see examples [here](https://www.tutorialspoint.com/the-best-way-to-check-if-a-file-exists-using-standard-c-cplusplus). It was just a matter of Precaution.

**Comment by bundle555** [comment]
thanks.

**Pull request merged**
